markdown: kramdown

kramdown:
    use_coderay: true

# user defined variables

# entry-type
# [ default, in-progress, deprecated, in-discussion, marked-to-delete ]
entry-type: default

# core url
url: "http://php-de.github.io"

# disabled by mermshaus for perma-urls ( noted by tr0y )
relative_permalinks: false

# global order id for unavailable orderId-Entries on guides
# the orderId must be between 0 and 25. the global definition of this value sort automaticly
# undefined entries after all defined entries.
orderId: 26

# page groups

groups:

    - name: "Einführung"
      path: "/introduction"
      desc: "Grundlegende Informationen zum Einstieg in PHP"
      anchor: "introduction"

    - name: "Allgemein"
      path: "/general"
      desc: "Allgemeine Themen rund um PHP"
      anchor: "general"

#    - name: "Entwicklungs Umgebung"
#      path: "/dev-enviroment"
#      desc: "XAMPP, LAMPP, VirtualBox, ZendServer & Co."
#      anchor: "dev-enviroment"

    - name: "Code-Optimierung"
      path: "/code-optimizing"
      desc: "Code-Optimierung von A bis Z."
      anchor: "code-optimizing"

    - name: "Sicherheit"
      path: "/security"
      desc: "Allgemeine Themen rund um die Sicherheit"
      anchor: "security"

    - name: "Debugging"
      path: "/debugging"
      desc: "Auf Fehlersuche"
      anchor: "debugging"

    - name: "URL / Dateisystem"
      path: "/url-filesystem"
      desc: "Informationen rund um die URL und dem Dateisystem"
      anchor: "url-filesystem"

    - name: "Request-Handling"
      path: "/request-handling"
      desc: "Wissenswertes über das Request Handling in PHP."
      anchor: "request-handling"

    - name: "Datenbanken"
      path: "/database"
      desc: "MySQL & Co."
      anchor: "database"

    - name: "E-Mail"
      path: "/email"
      desc: "Wissenswertes über den Umgang mit E-Mail-Adressen, Mail-Servern, und Mailer-Klassen."
      anchor: "email"

    - name: "Formularverarbeitung"
      path: "/form"
      desc: "Rund um die Erstellung, Verarbeitung, Validierung, etc. von Formularen"
      anchor: "form"

    - name: "Objektorientierte Programmierung (OOP)"
      path: "/oop"
      desc: "OOP unter PHP"
      anchor: "oop"

    - name: "Standard Implementierungsansätze"
      path: "/implement-approach"
      desc: "Gezielte Lösungsansätze für oft gefragtes"
      anchor: "implement-approach"
